package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"pz1.2/services/tasks/graph/model"
	"pz1.2/services/tasks/internal/service"
)

func toGQLTask(t *service.Task) *model.Task {
	var desc, dueDate, createdAt *string
	if t.Description != "" {
		desc = &t.Description
	}
	if t.DueDate != "" {
		dueDate = &t.DueDate
	}
	if t.CreatedAt != "" {
		createdAt = &t.CreatedAt
	}
	return &model.Task{
		ID:          t.ID,
		Title:       t.Title,
		Description: desc,
		DueDate:     dueDate,
		Done:        t.Done,
		CreatedAt:   createdAt,
	}
}

func derefStr(p *string) string {
	if p == nil {
		return ""
	}
	return *p
}

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, input model.CreateTaskInput) (*model.Task, error) {
	req := service.CreateTaskRequest{
		Title:       input.Title,
		Description: derefStr(input.Description),
		DueDate:     derefStr(input.DueDate),
	}
	task, err := r.TaskService.Create(ctx, req)
	if err != nil {
		return nil, err
	}
	return toGQLTask(task), nil
}

// UpdateTask is the resolver for the updateTask field.
func (r *mutationResolver) UpdateTask(ctx context.Context, id string, input model.UpdateTaskInput) (*model.Task, error) {
	req := service.UpdateTaskRequest{
		Title:       input.Title,
		Description: input.Description,
		DueDate:     input.DueDate,
		Done:        input.Done,
	}
	task, err := r.TaskService.Update(ctx, id, req)
	if err != nil {
		return nil, err
	}
	return toGQLTask(task), nil
}

// DeleteTask is the resolver for the deleteTask field.
func (r *mutationResolver) DeleteTask(ctx context.Context, id string) (bool, error) {
	if err := r.TaskService.Delete(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context) ([]*model.Task, error) {
	tasks, err := r.TaskService.GetAll()
	if err != nil {
		return nil, err
	}
	out := make([]*model.Task, len(tasks))
	for i, t := range tasks {
		out[i] = toGQLTask(t)
	}
	return out, nil
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, id string) (*model.Task, error) {
	task, err := r.TaskService.GetByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("task not found: %s", id)
	}
	return toGQLTask(task), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
